image: node:10.15.3

stages:
  - build
  # - deploy

build stage:
  stage: build
  cache:
    paths:
    - node_modules/
    - .yarn
  only:
    - merge_requests
  before_script: 
    - yarn config set cache-folder .yarn
    # Install dependencies
    - yarn install --ignore-scripts --ignore-engines
  script:
    # Install angular
    - yarn add @angular/cli@7.2.3 --ignore-scripts --ignore-engines
    # Rebuild SASS
    - npm rebuild node-sass
    # # Build App
    - yarn run build
  artifacts:
    paths:
      # Build folder
      - dist/browser/
    expire_in: 1 hour

# deploy stage:
#   image: python:latest
#   stage: deploy
#   only:
#     - merge_requests
#   script:
#     - pip install awscli
#     - aws s3 sync ./dist/browser s3://sevenforone
