export enum EventEnum {
	CONNECT = "connect",
	DISCONNECT = "disconnect",
	REGISTER_USER = "REGISTER_USER",
	CLOSE_SESSION = "CLOSE_SESSION",
	GROUP_ACTIVITY_10 = "group-activity-10",
  WIN_EVENT = 'WIN_EVENT',
  PLAYERS_ONLINE = 'PLAYERS_ONLINE',
  JOIN_GROUP = 'JOIN_GROUP',
  UPDATE_PURCHASE_HISTORY_USER = 'UPDATE-PURCHASE-HISTORY-USER',
  TOP_WINNER = 'TOP_WINNER'
}
